

USE airbnb_clone;


ALTER TABLE properties
ADD COLUMN IF NOT EXISTS street_address VARCHAR(255) AFTER location,
ADD COLUMN IF NOT EXISTS city VARCHAR(100) AFTER street_address,
ADD COLUMN IF NOT EXISTS state VARCHAR(100) AFTER city,
ADD COLUMN IF NOT EXISTS zip_code VARCHAR(20) AFTER state;

ALTER TABLE properties
ADD COLUMN IF NOT EXISTS check_in_time TIME DEFAULT '15:00:00' AFTER max_guests,
ADD COLUMN IF NOT EXISTS check_out_time TIME DEFAULT '11:00:00' AFTER check_in_time;
DESCRIBE properties;
